project:
  type: book
  output-dir: docs

execute:
  echo: true
  #eval: true
  warning: false
  message: false

book:
  title: "Interpretable Model Meets Local Explanation: A Comparison of LIME and Random Forest in Edibility Prediction Based on Bank Marketing Data"
  author:
    - Yanhang Zou (yz4821)
  repo-url: https://github.com/HannahZou/project1.git
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - 5293_projcode.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


