# Data

## Data Information
The data is related with direct marketing campaigns of a Portuguese banking institution. The marketing campaigns were based on phone calls. Often, more than one contact to the same client was required, in order to access if the product (bank term deposit) would be ('yes') or not ('no') subscribed. 
The classification goal is to predict if the client will subscribe (yes/no) a term deposit (variable y).

```{r}
library(ucimlrepo)
library(dplyr)
library(caret)
library(randomForest)
library(lime)
library(fastshap)
library(ggplot2)
library(Matrix)
library(vip)
# Load the dataset
bank <- fetch_ucirepo("Bank Marketing")
df <- bind_cols(bank$data$features, y = bank$data$targets$y)

# Encode categorical features as factors
df[] <- lapply(df, function(col) if (is.character(col) || is.logical(col)) as.factor(col) else col)

# Remove high-cardinality categorical variables
valid_cols <- sapply(df, function(col) !is.factor(col) || nlevels(col) <= 20)
df <- df[, valid_cols]

# Ensure target variable is a factor
df$y <- as.factor(df$y)
head(df)
```

## Description

The dataset includes 45,211 observations and 17 predictor variables, encompassing both categorical and numeric features such as:

-   Client Attributes: age, job, marital, education
-   Banking Information: default, housing, loan
-   Contact Details: contact, month, day_of_week, duration
-   Campaign Metrics: campaign, pdays, previous, poutcome

The target variable, y, is binary and indicates whether the client subscribed to a term deposit (yes or no). First, we imported the dataset by `ucimlrepo` R package. Then, all categorical variables were converted to factors for compatibility with the randomForest, lime, and Fastshap packages. And the high-cardinality categorical features (with more than 20 unique levels) were removed to simplify analysis and reduce sparsity in local surrogate models.


